version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    container_name: api
    volumes:
      - ./api/:/usr/src/app
      - /usr/src/app/node_modules
