FROM node:16

WORKDIR /usr/src/app

ENV ISSUER="https://ava-ai.eu.auth0.com/"
ENV AUDIENCE="https://api-route.com"
ENV JWKS_URI="https://ava-ai.eu.auth0.com/.well-known/jwks.json"

RUN npm i ts-node-dev -g

COPY package*.json ./

RUN npm ci

COPY . .

ENV PORT=3001

EXPOSE $PORT

CMD [ "ts-node-dev", "main.ts" ]