name: Ava CI

on:
  push:
    branches: [ main ]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Run unit tests
      run: >
        cd containers/api &&
        npm i &&
        cd ../../ &&
        make unit-tests

  deploy:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Setup Docker
        run: gcloud auth configure-docker -q

      - name: Deploy API
        run: make deploy-api
