auth0_client_id: ENC[AES256_GCM,data:45mLA6ULkPJXM0qwCzkXVmIANTudUTnQfGNuvRiMuHw=,iv:CNUa10A8U03/Xh6jP4ST6RwVe/E233zRqxPoS5MEXFM=,tag:TBciH/LDCAKCYy4mMBZN+Q==,type:str]
auth0_client_secret: ENC[AES256_GCM,data:KpKKWaJXMne8z84bXytqUvK1Yv4zJr+bq5SoRANcauPnKuZuzc5xO+3Sbf/CMuy6iH0qvgWBzXpaPkvWodTc0g==,iv:Q4ZdG4T6mh3gy3QPmZaLK7bNjbN4VCmXPj6IIwPVsH4=,tag:xM7/oJUCC6rs3ulcY6AhNw==,type:str]
auth0_domain: ENC[AES256_GCM,data:1qKfNHtWbyJFU/MLZXwzk/WV6RZVjwU=,iv:JDgIC+iMt/xc2CbhUcp9iUvYPGNdWdWawKnCm9bsqJ0=,tag:L9ltJHjUMnh9CdoR/6jyDQ==,type:str]
onprem_host: ENC[AES256_GCM,data:EturIbL+vGH3bAE=,iv:kdGuzssXjBpV31N4/D89Ts7LnnOYJ/jHNv03v4tb75U=,tag:mRtTBJYJ08ToU8KkVjOOYQ==,type:str]
POSTGRES_USER: ENC[AES256_GCM,data:qbNwPQ==,iv:L6QxaIO7lgmXQvip/lHRs0S0rLzQ4exZ5lhdp1YzBfY=,tag:cZ5AXRonKzMCMPCuWi6zgw==,type:str]
POSTGRES_PASSWORD: ENC[AES256_GCM,data:7fRI16z7QJj3iRMnog==,iv:XKQketZWQCakaib3XtYLDtFmuBNFjhK90vFueVxU85Q=,tag:jwB55RFWLvONNS35I2iivQ==,type:str]
DATABASE_URL: ENC[AES256_GCM,data:g9/Lvc6p5Dr4CWAGtDQ4ofQ2mTrVbVHtmLoVj6in9hOYeWY/0kG3oVJAC/OFmbCr6igW8w==,iv:3B3iMRg1BoB4tgd8cE45QqbGudy1zvncC2kpi981x2c=,tag:nKr1Z1Rmk+Gz2QixlQVqBA==,type:str]
SHADOW_DATABASE_URL: ENC[AES256_GCM,data:o0ERfWZJpHurjGtDLqaBnT7mcBFpTiV+BvLMm5+MrM3RrU6qD07qCDrNgxtjPTGSoqkh5g==,iv:L2PhzLx3ddFwu6xfWtJnjek3IOwXlufEBsZsD5yb3ew=,tag:P3gkeyfQaUmy2o7lziVuSw==,type:str]
ISSUER: ENC[AES256_GCM,data:tDXdV5JTzPloohXhH6Jr/RKX2WhDIZ2mnZ86oS7yO9s=,iv:t6kCdEKK3AoWzHTdO5F50N2wZX0preGUT1qhiGa8RvU=,tag:lQ4jTyegybY692/BcIdT/g==,type:str]
AUDIENCE: ENC[AES256_GCM,data:qrOM0HXCQtzhbIfb15M0AScjc3Du,iv:A28vUl0xdkLLTKRMUj7y1Zc2smBBEHhAOmTEqHH/rYg=,tag:OGWsPvsUp2lMjjIQFoc95Q==,type:str]
JWKS_URI: ENC[AES256_GCM,data:tRipB4+HcNdylzNmQtY7Voqvaxa6wF8W23vByAiNOIN7gSvH1OxeB3bNBdUgaqaIESoLoYY=,iv:TBDSGPI1UZk7pPChB+VvdyteToWl4ob8/7Hjib6wML4=,tag:tu4gbzcoCX+NgCIgn2vjcQ==,type:str]
PLAYGROUND_ENABLED: ENC[AES256_GCM,data:26ps3AY=,iv:AiaX7G8IOZnqsjKx2G539cl0IUDy4wsIgM1ZEPd4QdE=,tag:MIPKdRsW5/eOhtRb5hhBSQ==,type:bool]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ava-ai-322720/locations/us-central1/keyRings/ava-main-keyring/cryptoKeys/ava-main
          created_at: "2021-12-23T20:33:54Z"
          enc: CiQAk36sfL3fRwgGaJuWPbA0kriKcv2bRxc/yzAqS8jcJhcL+JESSQBbAkhVocliHONrmSUyfAJoZANtxVWk0lAvU3EiDCrI32h6z/NF+bX8lFou/57SNaQnT6Id4ksmOlXYji0BkWIcjwZ/tEIbEVw=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-30T23:45:28Z"
    mac: ENC[AES256_GCM,data:vskSvm8mUHQsuQ0znR6gGGJl833o8fMBPYlH9I/YHDAZG9Dtw314hg8YV5BzLzvYpHYzQqVvsfMZVfliPszAXH3lA1iW3+hznA47CrSSPwTHEhsHmKR+d8+aJv5ef+0lvctVL2DTzDLos+lGomI0DhN5jEpEGYVfhA2qxCuxhyM=,iv:IbrxvMEVLT6H4g48yQxWMNWi4ZaKGj1tUVQU5qqWovU=,tag:yntP3hzBF7VZLu/jAA5AFA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
