auth0_client_id: ENC[AES256_GCM,data:Y6Nq7OtsUG5FFTfbUAIU/rgU/BoYlx9U+ORJUeY7ISU=,iv:zNJWDvOmRPErV+lhq8B+LAJyICMi5j4Y9lc2BT8I9M8=,tag:Zwj6svoTaB0vnBa9QKuAFA==,type:str]
auth0_client_secret: ENC[AES256_GCM,data:mIAqB0UqbZAqxGCxLu7NQLAJWmgRPgcjqdVYF009C4a8gu84MGB/FsNXwSCznOMChz03JR423NVW3JVgKsv0AA==,iv:GUP4NKXCWsq/fcLAcSmO2wbPy249zJoLTyTvTFermL8=,tag:iHdcAg1NaNUtubm7RzinZg==,type:str]
auth0_domain: ENC[AES256_GCM,data:w8CJJztMXx9oGD2DiM6FQaAj+Q==,iv:zX2CHoY8BQaGNX2sLyvxeKFrCcyenbcrTvEJg+9l8dg=,tag:P2PSTHpsKdxKyi5bxt+KTw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ava-ai-322720/locations/us-central1/keyRings/ava-keyring/cryptoKeys/ava-main
          created_at: "2021-12-19T15:06:01Z"
          enc: CiQAHOCBo4yX4RsYz4lv2/2nZc+gXSBDlAaWiCzlOfs9WWQEdwESSQDnQ+/84tRLBPtkg/QE6o3aLaqWBDKtLS7/1BB83oewvFynBvZNCHpkQ6mP/9C7z55Kixv47o+EgZAmR/+AIwJ7sJUjavVCyEU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-19T15:13:43Z"
    mac: ENC[AES256_GCM,data:mmfpxtIgvgrREhFmL6lf8aeIGSZCXswFtP0IVZ60ewaGbwSvENUYOXypanH6sS0L9nz4JkJCLKU6rckz1zaqS/gxt+UhowlTLMVOMSJsytnXGr+zCVzPr1Y3O/gF4Lg7dkmQ4cQ+y6CMGjTeE3Qu1/BsRfRZm1YehQ66i5Nc2xk=,iv:Npmi/sCgZVHVWZhwLgGsp1LZwCHBpRfQUFmR9tMaFhE=,tag:RrbN3KgQWE4j0/dY7IBERw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
