auth0_client_id: ENC[AES256_GCM,data:45mLA6ULkPJXM0qwCzkXVmIANTudUTnQfGNuvRiMuHw=,iv:CNUa10A8U03/Xh6jP4ST6RwVe/E233zRqxPoS5MEXFM=,tag:TBciH/LDCAKCYy4mMBZN+Q==,type:str]
auth0_client_secret: ENC[AES256_GCM,data:KpKKWaJXMne8z84bXytqUvK1Yv4zJr+bq5SoRANcauPnKuZuzc5xO+3Sbf/CMuy6iH0qvgWBzXpaPkvWodTc0g==,iv:Q4ZdG4T6mh3gy3QPmZaLK7bNjbN4VCmXPj6IIwPVsH4=,tag:xM7/oJUCC6rs3ulcY6AhNw==,type:str]
auth0_domain: ENC[AES256_GCM,data:1qKfNHtWbyJFU/MLZXwzk/WV6RZVjwU=,iv:JDgIC+iMt/xc2CbhUcp9iUvYPGNdWdWawKnCm9bsqJ0=,tag:L9ltJHjUMnh9CdoR/6jyDQ==,type:str]
onprem_host: ENC[AES256_GCM,data:EturIbL+vGH3bAE=,iv:kdGuzssXjBpV31N4/D89Ts7LnnOYJ/jHNv03v4tb75U=,tag:mRtTBJYJ08ToU8KkVjOOYQ==,type:str]
POSTGRES_USER: ENC[AES256_GCM,data:qbNwPQ==,iv:L6QxaIO7lgmXQvip/lHRs0S0rLzQ4exZ5lhdp1YzBfY=,tag:cZ5AXRonKzMCMPCuWi6zgw==,type:str]
POSTGRES_PASSWORD: ENC[AES256_GCM,data:7fRI16z7QJj3iRMnog==,iv:XKQketZWQCakaib3XtYLDtFmuBNFjhK90vFueVxU85Q=,tag:jwB55RFWLvONNS35I2iivQ==,type:str]
DATABASE_URL: ENC[AES256_GCM,data:g9/Lvc6p5Dr4CWAGtDQ4ofQ2mTrVbVHtmLoVj6in9hOYeWY/0kG3oVJAC/OFmbCr6igW8w==,iv:3B3iMRg1BoB4tgd8cE45QqbGudy1zvncC2kpi981x2c=,tag:nKr1Z1Rmk+Gz2QixlQVqBA==,type:str]
SHADOW_DATABASE_URL: ENC[AES256_GCM,data:eQOI8w3QMGw3UigXP8zp1QWmPfsYxq/OyMZ6NuQY3vHpox3QjCckh24lqdlDw7XDM04UAg==,iv:Qmbnz7LXit+9hcGRxMOPMugxGG93MPmGcPiQxt0/bt0=,tag:wDKuvvj4elJ1K8N5sm38Yg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ava-ai-322720/locations/us-central1/keyRings/ava-main-keyring/cryptoKeys/ava-main
          created_at: "2021-12-23T20:33:54Z"
          enc: CiQAk36sfL3fRwgGaJuWPbA0kriKcv2bRxc/yzAqS8jcJhcL+JESSQBbAkhVocliHONrmSUyfAJoZANtxVWk0lAvU3EiDCrI32h6z/NF+bX8lFou/57SNaQnT6Id4ksmOlXYji0BkWIcjwZ/tEIbEVw=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-23T20:33:55Z"
    mac: ENC[AES256_GCM,data:AFCaugCJ1W8qLGsZbM9VrhQUd+3TRw4t9ot73cxfdnAx9YH/SxCVifCZqZ3Oxq+dctcpqBBbNyaW7Ep59c3/SNldb2Ao70ZtfadbF5DCE+DHXWKNyLNglzEgOaffi9G6EAoUqOdd1Jh/2N+ehQFa4sobmfL6pqFku2ibcVbSbSg=,iv:fu/j5vXc8GbxCD64L186EQt+jUNXT7fpPutRugFHvkw=,tag:jUyb2SV8ZfvRQD7w4R9KtQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
