auth0_client_id: ENC[AES256_GCM,data:D1Lr13VjLXBWlmCdYYed/MR29oYqb/cqk8dhJOFl4qs=,iv:Jt5CSQwFIKZHeoNMEYjm2mhTU4RB5O3MjccEK2HstFs=,tag:3bL3PvsyBzh65MlrKCs4Qg==,type:str]
auth0_client_secret: ENC[AES256_GCM,data:MBxQ9C0OQ6xRBipod3kKrmRsRY7XSBKbKKxMn7ccAf6eW0MC8+1WRWwPHRc2ncMvjobJWNxG2yUtZAQuTqdDEA==,iv:z1j2vmMy4f/Xad/FY95SHMqm13lRU2cJ2jAV8Sq81QM=,tag:F/Pwnr2Wc4mD3ItM2qzV3A==,type:str]
auth0_domain: ENC[AES256_GCM,data:2I/sCCHw/cruMYGQRoiyB3f81Q==,iv:AQKTG6dYef8a2OLNR4ZdcNt+YBeu5VdHGRmcUT8QCWw=,tag:QORfqpgd+gV0qifAklWlwg==,type:str]
onprem_host: ENC[AES256_GCM,data:Yv17KUm/ZoFNT5I=,iv:fx0mSfPhHxmpCAqJRziolE5vHqGAvbIk2iK5Tvl8tmQ=,tag:4eHt4FNyED9cgy/sYuSEnw==,type:str]
POSTGRESQL_USER: ENC[AES256_GCM,data:XFATnw==,iv:zSeHlKnAJliEkd93q/Gtt7mFQ3+90hDSIbK0Js3cynY=,tag:5aKZUa+rd2rcqeFdaDPetw==,type:str]
POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:pKFdEqRHvGzTwbeqvQ==,iv:51A4XrPSVs7yDy0M+elyuc9rv/8EbAhXF6NeUWdh9To=,tag:Ya2wBZvmt9/aiVXhkU2AMw==,type:str]
DATABASE_URL: ENC[AES256_GCM,data:daY5E/SmvYR2DmKvW4pPSnVvz9dJzSv2TVgAYC+t+vN2iitJUSK8SJumV95JqQ==,iv:8e0HwiMQ149A5uWF5oG1fUrly+p3N3FvaTwttSmhsjo=,tag:WU7Xt2paiDirPO7dMKHjtA==,type:str]
SHADOW_DATABASE_URL: ENC[AES256_GCM,data:ONH9FTo1Rhay9NqOgrVDBGGvRgA1EFRye2rHcP9MRreLXAZqS14kj3odYnIyDyw=,iv:bn9Hytmxz/IvsEWHMl/KNzVJofr0xsPGH3D52GvwRMc=,tag:iYA7yUvlhfIJx1TVwqj9lg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ava-ai-322720/locations/us-central1/keyRings/ava-keyring/cryptoKeys/ava-main
          created_at: "2021-12-19T17:05:42Z"
          enc: CiQAHOCBo2MScBJzvw/eVivc2VPYkfqsAkje1naT1R0XYAC9AB0SSQDnQ+/8i9BW6+YZgEAtYKuNqZ7DQBJwpbpB9ZjSz4ahyPV/+sjKoAYCYfFCYZtqvb/6uYvig65+AeWJ0dc/3vUlvubAve9RmDk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-19T17:05:43Z"
    mac: ENC[AES256_GCM,data:dHJPYfv2Qnp0dqCKlJ806EQ03zJjAjoIwxDwtY3pPg+mohgsQxg9QAEbNaDXsBo/+ZI8wVsIWXry4wXM/YZMFGJsdny/jdnWE1ZG72uXGxOydc3i4du+phSznRdlHWiOcBLQ9oeVgwz2cF7RKEoDk2y0BcYikg+DAWfi1ieF9zU=,iv:Q/7TUstUvyhJwGw54QWhEoofXE70GHUdGdOg2nDKPy0=,tag:TaZYXWwGhESrIlHB85gvXw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
