auth0_client_id: ENC[AES256_GCM,data:D1Lr13VjLXBWlmCdYYed/MR29oYqb/cqk8dhJOFl4qs=,iv:Jt5CSQwFIKZHeoNMEYjm2mhTU4RB5O3MjccEK2HstFs=,tag:3bL3PvsyBzh65MlrKCs4Qg==,type:str]
auth0_client_secret: ENC[AES256_GCM,data:MBxQ9C0OQ6xRBipod3kKrmRsRY7XSBKbKKxMn7ccAf6eW0MC8+1WRWwPHRc2ncMvjobJWNxG2yUtZAQuTqdDEA==,iv:z1j2vmMy4f/Xad/FY95SHMqm13lRU2cJ2jAV8Sq81QM=,tag:F/Pwnr2Wc4mD3ItM2qzV3A==,type:str]
auth0_domain: ENC[AES256_GCM,data:2I/sCCHw/cruMYGQRoiyB3f81Q==,iv:AQKTG6dYef8a2OLNR4ZdcNt+YBeu5VdHGRmcUT8QCWw=,tag:QORfqpgd+gV0qifAklWlwg==,type:str]
onprem_host: ENC[AES256_GCM,data:Yv17KUm/ZoFNT5I=,iv:fx0mSfPhHxmpCAqJRziolE5vHqGAvbIk2iK5Tvl8tmQ=,tag:4eHt4FNyED9cgy/sYuSEnw==,type:str]
POSTGRES_USER: ENC[AES256_GCM,data:mmGf+Q==,iv:1Uv3wIMV7nQCCPa5iD1WXDRBJt6fueLhmZLImo/T+ok=,tag:xzj6Npbdxd9rMCBytOWaiw==,type:str]
POSTGRES_PASSWORD: ENC[AES256_GCM,data:fHWg4LIJ5+gzNWJX0A==,iv:MpHzNTNZGFZp/+JEu24sOHmOARNudqbvfg5QQn1at4Y=,tag:iquOzcnCTSJXtsum/TagJQ==,type:str]
DATABASE_URL: ENC[AES256_GCM,data:H/8V+w2FR7gsPk7RxSz3eC6g9h69tYVvK3XyQRj9glKwWSp9fPo9OswaXlv0dz0ROF10gg==,iv:B//nZE1FQ0o+UmrrR0+6qEbS86QtW4lsm4GYmUFWsaI=,tag:MBqp7YdPvQclXVnWwRQAfQ==,type:str]
SHADOW_DATABASE_URL: ENC[AES256_GCM,data:8Mk4VOnv5vR2B45rHBPMoK/I3bzXX7yiJ8e8gRpG3Z5rccU3mRqCbnDPLpLkXjRMhFusAg==,iv:iVRWJ3rqjhslNTjgaLsOZA0sdP9LvX+yA1u2TBRl26o=,tag:xxdSloTocZEnm1N8bF3krQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ava-ai-322720/locations/us-central1/keyRings/ava-keyring/cryptoKeys/ava-main
          created_at: "2021-12-19T17:05:42Z"
          enc: CiQAHOCBo2MScBJzvw/eVivc2VPYkfqsAkje1naT1R0XYAC9AB0SSQDnQ+/8i9BW6+YZgEAtYKuNqZ7DQBJwpbpB9ZjSz4ahyPV/+sjKoAYCYfFCYZtqvb/6uYvig65+AeWJ0dc/3vUlvubAve9RmDk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-22T21:03:17Z"
    mac: ENC[AES256_GCM,data:8o1FJdUcE/E5TLyu9r7QRJtdiv2AXS9M1nuS8Qlb2ujaLDXhywChC/Rv7eG6SpO351E9Zf4K5jTVpxiFHV0zFx1IGd1U6uM898qVXfX44C8mGIImrlKCp0WvmBT64QJF3U257EaP7NXKE09mz62UOxXqqYcL6//8Bc0K1k49v7I=,iv:uUcVehnBB1xwH46DqlNGHvFvsxd403tnOJpIi7mvSLo=,tag:CkosMsbBcCzJUzIi0PZMDw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
