auth0_client_id: ENC[AES256_GCM,data:45mLA6ULkPJXM0qwCzkXVmIANTudUTnQfGNuvRiMuHw=,iv:CNUa10A8U03/Xh6jP4ST6RwVe/E233zRqxPoS5MEXFM=,tag:TBciH/LDCAKCYy4mMBZN+Q==,type:str]
auth0_client_secret: ENC[AES256_GCM,data:KpKKWaJXMne8z84bXytqUvK1Yv4zJr+bq5SoRANcauPnKuZuzc5xO+3Sbf/CMuy6iH0qvgWBzXpaPkvWodTc0g==,iv:Q4ZdG4T6mh3gy3QPmZaLK7bNjbN4VCmXPj6IIwPVsH4=,tag:xM7/oJUCC6rs3ulcY6AhNw==,type:str]
auth0_domain: ENC[AES256_GCM,data:1qKfNHtWbyJFU/MLZXwzk/WV6RZVjwU=,iv:JDgIC+iMt/xc2CbhUcp9iUvYPGNdWdWawKnCm9bsqJ0=,tag:L9ltJHjUMnh9CdoR/6jyDQ==,type:str]
onprem_host: ENC[AES256_GCM,data:EturIbL+vGH3bAE=,iv:kdGuzssXjBpV31N4/D89Ts7LnnOYJ/jHNv03v4tb75U=,tag:mRtTBJYJ08ToU8KkVjOOYQ==,type:str]
POSTGRES_USER: ENC[AES256_GCM,data:qbNwPQ==,iv:L6QxaIO7lgmXQvip/lHRs0S0rLzQ4exZ5lhdp1YzBfY=,tag:cZ5AXRonKzMCMPCuWi6zgw==,type:str]
POSTGRES_PASSWORD: ENC[AES256_GCM,data:7fRI16z7QJj3iRMnog==,iv:XKQketZWQCakaib3XtYLDtFmuBNFjhK90vFueVxU85Q=,tag:jwB55RFWLvONNS35I2iivQ==,type:str]
DATABASE_URL: ENC[AES256_GCM,data:KKiTn4f1DGaMSD4jfJF4qTTNwfG+UCgnDmatHvTgcXy1FW4b4KAgYGqut0PYONw=,iv:JAxNSd9kWkrLqtZRYu68gkkXP8MG0+nD1rLK7Mx6aYg=,tag:9hEV+TX11k74OFQK0l0Lqw==,type:str]
SHADOW_DATABASE_URL: ENC[AES256_GCM,data:Iq4CNST7s8ih18ZdoIFIk+6XhA/hQQ/y63I7HM4EfMig27sy736EsDISbd+WTg4=,iv:Dc6pk5zW/aFxw7MqHx34HlZBQJJiBlebD77ISGYgCmY=,tag:P0QVZEDRCtL1GkFdQMTxFQ==,type:str]
ISSUER: ENC[AES256_GCM,data:tDXdV5JTzPloohXhH6Jr/RKX2WhDIZ2mnZ86oS7yO9s=,iv:t6kCdEKK3AoWzHTdO5F50N2wZX0preGUT1qhiGa8RvU=,tag:lQ4jTyegybY692/BcIdT/g==,type:str]
AUDIENCE: ENC[AES256_GCM,data:qrOM0HXCQtzhbIfb15M0AScjc3Du,iv:A28vUl0xdkLLTKRMUj7y1Zc2smBBEHhAOmTEqHH/rYg=,tag:OGWsPvsUp2lMjjIQFoc95Q==,type:str]
JWKS_URI: ENC[AES256_GCM,data:tRipB4+HcNdylzNmQtY7Voqvaxa6wF8W23vByAiNOIN7gSvH1OxeB3bNBdUgaqaIESoLoYY=,iv:TBDSGPI1UZk7pPChB+VvdyteToWl4ob8/7Hjib6wML4=,tag:tu4gbzcoCX+NgCIgn2vjcQ==,type:str]
PLAYGROUND_ENABLED: ENC[AES256_GCM,data:26ps3AY=,iv:AiaX7G8IOZnqsjKx2G539cl0IUDy4wsIgM1ZEPd4QdE=,tag:MIPKdRsW5/eOhtRb5hhBSQ==,type:bool]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ava-ai-322720/locations/us-central1/keyRings/ava-main-keyring/cryptoKeys/ava-main
          created_at: "2021-12-23T20:33:54Z"
          enc: CiQAk36sfL3fRwgGaJuWPbA0kriKcv2bRxc/yzAqS8jcJhcL+JESSQBbAkhVocliHONrmSUyfAJoZANtxVWk0lAvU3EiDCrI32h6z/NF+bX8lFou/57SNaQnT6Id4ksmOlXYji0BkWIcjwZ/tEIbEVw=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-31T11:59:26Z"
    mac: ENC[AES256_GCM,data:ivN/K2jRmZ6e0G2VUVgXWn8K6pw84nD/DDjq8UVlxYj6AFXhVFU/pFXgZxi07IwBwCswUc6VvXMGThfIhvKp230MwyrhVi+HbmWhh1WL8God2YAZJ7viHRYZR/8vhQwi8GjqxpvwH2iF1QGH795UTYVSgcUQ8Rh7ffAALZP6vuU=,iv:468iYI7iXuDm/2uFmrsyyeTdw7FAVD1IPH+ifZDFJjs=,tag:U/oLn8lEto7yUyN2XPZ8CA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
