auth0_client_id: ENC[AES256_GCM,data:9DpkPUvJpCoTE2aub+5/a3dDTiSblAT1z9/ydOcaTMs=,iv:964h3qmsJxD4FZ2ABOxDsCD77r+quaOcA4MXoUuMYnE=,tag:J6Uk7ra6llCKOOVpkcJijw==,type:str]
auth0_client_secret: ENC[AES256_GCM,data:Dw1WgHQq67bg3vM4g2DJqtyL3xxamoO71KXPMH0lhZEXdFtLCGm+nzai4k7jq3YxpoPY2hV/QjBK20FyBVyUIQ==,iv:9baCm8yDS2C51Wrkf+yTJx/2m2E7o6ZmHUuUtgaAE0A=,tag:5WuJYFes+VRtiMbIj4/Kvw==,type:str]
auth0_domain: ENC[AES256_GCM,data:e/NFNp/53Fs/+Iw9ha6IPWARV1U1G/bY,iv:rzNiMyV3eAg4VyNG3m/JICl6SAb4azynRkY5J/Sp6Q0=,tag:NYPWCh8/oUZCFa4V6U1jXQ==,type:str]
onprem_host: ENC[AES256_GCM,data:BotmSlne3B4K5EU=,iv:twEWPKL+28AxfDkjRIXI43GL/z6xgJz0x7rEBmgopeE=,tag:8FJT/86HyMs0hp8yZNV/5Q==,type:str]
POSTGRES_USER: ENC[AES256_GCM,data:fWosrbcr,iv:wvHpAs3KddUGEt+zuOquWcaxkmkRyCXs/i+whnLJE4o=,tag:04yejrZLvTuBvZdavYlMGQ==,type:str]
POSTGRES_PASSWORD: ENC[AES256_GCM,data:odUT3TTTK1itheVEIqH2yfVGvRRLmceQvoRGKjUvOcXx894QflxB0TenG956XJQDPJAuVdwcjsUmjW7/3kF+Aw==,iv:Y5LIbC0w0fhQsKr/KHsVfWsIm1/G4d2JGgepAnKhNIY=,tag:LNbZJZ/fT5NHBBCgLb4KLg==,type:str]
DATABASE_URL: ENC[AES256_GCM,data:BzJaPK2Kjm/aa/CoPTJxfLKpen38yXuZqY+QiiVpydGNRyCRhJjjbBbM7v1bfhNlvB/KDAAa8OITULXw87eP6mJEKiGgPLSnSHqnn5vGSBs9ppl/0MN3PmVS7DIziuP6STls/Hj4gWi+vA==,iv:l6mend1JPN2tYofkJOCSiLrIQ2qPL8twNg8sxevCT1Y=,tag:yLVTA349ejhS1xiMvXwyWA==,type:str]
SHADOW_DATABASE_URL: ENC[AES256_GCM,data:1NaH1iMypjEtw6bHqSlnQrdvQn3Sfie9sumdTPEJ7qk0jln3gFzANEKoXucW6D0queN0N1GRhbxHzPKAATA3uMEY8eudUDILOzBv7AH55c1xIlvUeA9owMJHAZs04GGVtzmgPO4xAmTn,iv:MKPPUWLkeiVAm8Q0ofBg5CzE43bE6/od3N4xgxrDwoc=,tag:bhzPNI5RDg0HgeeaftrQrQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ava-ai-322720/locations/us-central1/keyRings/ava-main-keyring/cryptoKeys/ava-main
          created_at: "2021-12-23T20:34:32Z"
          enc: CiQAk36sfELWL05L3MTL24sK7L3G9dA3jQ/fkpt3q2HR42G10R4SSQBbAkhVKwVzkxjmW6kPa8oE91x1zQPJdprjOkVj/QITS3P6r9HHQqxRXDIUrKMkUf3VoU+nm4ZAAxOGa62G0zORGwh8EUyUivY=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-23T20:34:33Z"
    mac: ENC[AES256_GCM,data:o1L4UF21WkXFqEF4wFN3D0txQ1rnH+RymCxlAdN+Rx6wycWIGGrX20kjHJ+7BrwRBX4ZIZoZbFFGohhkfUyoEezHrv/2h7wbZRwBXdpHMCj9cOUkwKhPz9wXP8XyYkX5lJ1Zf+ioTZRCfpBSPNcN7nuH9TE63AkOIh2xV4yNXHE=,iv:GVaPBMvnFoC3MbWoeoG75a7nKyMdiaeNVn9LiXeupew=,tag:w6/FqjNH6OrqTSZpynbtzA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
