auth0_client_id: ENC[AES256_GCM,data:9DpkPUvJpCoTE2aub+5/a3dDTiSblAT1z9/ydOcaTMs=,iv:964h3qmsJxD4FZ2ABOxDsCD77r+quaOcA4MXoUuMYnE=,tag:J6Uk7ra6llCKOOVpkcJijw==,type:str]
auth0_client_secret: ENC[AES256_GCM,data:Dw1WgHQq67bg3vM4g2DJqtyL3xxamoO71KXPMH0lhZEXdFtLCGm+nzai4k7jq3YxpoPY2hV/QjBK20FyBVyUIQ==,iv:9baCm8yDS2C51Wrkf+yTJx/2m2E7o6ZmHUuUtgaAE0A=,tag:5WuJYFes+VRtiMbIj4/Kvw==,type:str]
auth0_domain: ENC[AES256_GCM,data:e/NFNp/53Fs/+Iw9ha6IPWARV1U1G/bY,iv:rzNiMyV3eAg4VyNG3m/JICl6SAb4azynRkY5J/Sp6Q0=,tag:NYPWCh8/oUZCFa4V6U1jXQ==,type:str]
onprem_host: ENC[AES256_GCM,data:BotmSlne3B4K5EU=,iv:twEWPKL+28AxfDkjRIXI43GL/z6xgJz0x7rEBmgopeE=,tag:8FJT/86HyMs0hp8yZNV/5Q==,type:str]
POSTGRES_USER: ENC[AES256_GCM,data:fWosrbcr,iv:wvHpAs3KddUGEt+zuOquWcaxkmkRyCXs/i+whnLJE4o=,tag:04yejrZLvTuBvZdavYlMGQ==,type:str]
POSTGRES_PASSWORD: ENC[AES256_GCM,data:odUT3TTTK1itheVEIqH2yfVGvRRLmceQvoRGKjUvOcXx894QflxB0TenG956XJQDPJAuVdwcjsUmjW7/3kF+Aw==,iv:Y5LIbC0w0fhQsKr/KHsVfWsIm1/G4d2JGgepAnKhNIY=,tag:LNbZJZ/fT5NHBBCgLb4KLg==,type:str]
DATABASE_URL: ENC[AES256_GCM,data:s2tkBbX1XIwrc/c4RBZ6VYkH18q47y82L2udaWy8rsjLsk7LLtC2isFqMlbvxrLt05TMgImeswqtL+l07e45FssVqRnMWZKZgrKlkjoFDVEuaLZj5fas2IlzZp3ztVKi3veLCyzCSQvr43Y=,iv:v2/06LnRi3khetI/T9gQLrR9Gdfnvo3dDK1CbNaAAVQ=,tag:GuPT45cEsDrN+HCa6BwkJQ==,type:str]
SHADOW_DATABASE_URL: ENC[AES256_GCM,data:lq52oF+9I8SRAJHnQVsn5jmHpVkGm8SuzPKgPhRMk2PUiH19974GlY/pRi+IhyrIJXq0LcQ9f9gY40vlfPRNapgMKu9WYsnPwVnxjOpLQXsPcXm/xnXxsP7p7faAFPUJ5ntz69dBZ+T2HQ==,iv:2E+lJa5ApKyeNykKm0SG7k9MtZl8dg7QX+yUeR5xMZg=,tag:cTLngI9t90JGKPDaNnVXJg==,type:str]
ISSUER: ENC[AES256_GCM,data:vMtBSq/olN7ouuqEF3tntQSAWNRs9uoaN3sTupO9ngxB,iv:DH1C25R0AAdcqO4wD7iWlkRWK69RN3VOrl446eRI708=,tag:oTEYaxbYaGJag+CGoECsCg==,type:str]
AUDIENCE: ENC[AES256_GCM,data:6uSHGJBKqNMYvwedR09rzm5D4sVa,iv:blKyanGskYxXS1vxzqoycwvcdI9Qdr2nhn8O00am24o=,tag:i1km29/Nsvb8rkyYEztHOA==,type:str]
JWKS_URI: ENC[AES256_GCM,data:YqxcZKy9/2ozzkRUmTGDBfonOO/J+S1C/ZAJiUPQJ8nUrUosxzfkXeo3PhLk8UETTQ6WWU7B,iv:yTmxMmerbCBxMG+C55RCfT4/8ZHoZHHkhZ1HCDtOcro=,tag:SOJeGAAkwzWH9Tqi4g15tw==,type:str]
PLAYGROUND_ENABLED: ENC[AES256_GCM,data:Y3cG2LI=,iv:XR/CADjv7XPv+/MtFKzy5SUfxqJEFh4piaCvYLXaLD0=,tag:UL65Wx/F1bntPvyspMyVFA==,type:bool]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ava-ai-322720/locations/us-central1/keyRings/ava-main-keyring/cryptoKeys/ava-main
          created_at: "2021-12-23T20:34:32Z"
          enc: CiQAk36sfELWL05L3MTL24sK7L3G9dA3jQ/fkpt3q2HR42G10R4SSQBbAkhVKwVzkxjmW6kPa8oE91x1zQPJdprjOkVj/QITS3P6r9HHQqxRXDIUrKMkUf3VoU+nm4ZAAxOGa62G0zORGwh8EUyUivY=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-30T23:44:33Z"
    mac: ENC[AES256_GCM,data:CT0ODdURxhgr1YZfQVm1HwEtpLepDy/eUeX71av5dShN250FlL1bNLFxaEh76c+4EKV4n7GiAb1TUyl9kyd63PKu0Ot/SONvys8cWeAjCq2by2G6HZ3tt2dsppHXhZjU+iIp39JdQ9MciFE3MsSc0G6tEYrJoRFtofP0N5PxxYI=,iv:s3iByL8dy1g244/z3dLKKYNtZVoAgHAoI7iKwDtbWSg=,tag:RqKvhYvIq3LBbBdcW9cUEQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
